//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assist.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assist.Properties.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Authentication_2FactorPlaceholder {
            get {
                return ResourceManager.GetString("Authentication_2FactorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Authentication_LoginBtn {
            get {
                return ResourceManager.GetString("Authentication_LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifactor Code is not correct..
        /// </summary>
        public static string Authentication_MultifactorFail {
            get {
                return ResourceManager.GetString("Authentication_MultifactorFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Authentication_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Authentication_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Rito Login allows you to login to the riot website and then use Assist. Note: Google Login does not work..
        /// </summary>
        public static string Authentication_RitoInfo {
            get {
                return ResourceManager.GetString("Authentication_RitoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Note: Social Authentication does not function with Assist. To use a social login please login with a Riot Username and Password combo. If you do not have a Riot Username and Password combo with a social account, check your account details on the Riot Account Website to create a combo..
        /// </summary>
        public static string Authentication_RitoLogin_Notice {
            get {
                return ResourceManager.GetString("Authentication_RitoLogin_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string Authentication_SubmitBtn {
            get {
                return ResourceManager.GetString("Authentication_SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Username and Password allows you to directly login with your Riot Games Username and Password..
        /// </summary>
        public static string Authentication_UserInfo {
            get {
                return ResourceManager.GetString("Authentication_UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Riot Games Username and Password. All of the login information is sent to Riot Servers and Riot Servers only.
        ///
        ///If you get Error 403, this is a Riot Login Error that we cannot fix, we recommend updating your Windows to have a possiblity fixing the error and logging in with Assist..
        /// </summary>
        public static string Authentication_UsernameLogin_Notice {
            get {
                return ResourceManager.GetString("Authentication_UsernameLogin_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Authentication_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Authentication_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Assist, please select a way to login below..
        /// </summary>
        public static string Authentication_WelcomeInfoLabel {
            get {
                return ResourceManager.GetString("Authentication_WelcomeInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string Authentication_WelcomeLabel {
            get {
                return ResourceManager.GetString("Authentication_WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string Dashboard_Discord {
            get {
                return ResourceManager.GetString("Dashboard_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Dashboard_Support {
            get {
                return ResourceManager.GetString("Dashboard_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Account:.
        /// </summary>
        public static string DefaultAcc_Label {
            get {
                return ResourceManager.GetString("DefaultAcc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, If you are seeing this you have received a Forbidden Error while logging in. This is not something we can fix. This is a block by Riot. We are very sorry for this problem and we wish that one day there will be a fix. For now, there are only a few fixes that the community has thought of. 
        ///
        ///First: Update your Windows, this fixes the problem majority of the time.
        ///
        ///Second: Reset your Router.
        ///
        ///Otherwise, we are sorry and hope that one day you can use Assist..
        /// </summary>
        public static string Forbidden_Message {
            get {
                return ResourceManager.GetString("Forbidden_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string InitPage_Loading {
            get {
                return ResourceManager.GetString("InitPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Navigation_DashboardHover {
            get {
                return ResourceManager.GetString("Navigation_DashboardHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        public static string Navigation_ProgressionHover {
            get {
                return ResourceManager.GetString("Navigation_ProgressionHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Navigation_SettingsHover {
            get {
                return ResourceManager.GetString("Navigation_SettingsHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Navigation_StoreHover {
            get {
                return ResourceManager.GetString("Navigation_StoreHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDS IN.
        /// </summary>
        public static string NightMarket_EndsIn {
            get {
                return ResourceManager.GetString("NightMarket_EndsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIGHT MARKET.
        /// </summary>
        public static string NightMarket_Name {
            get {
                return ResourceManager.GetString("NightMarket_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Settings.
        /// </summary>
        public static string ProfileLaunchControl_LaunchSettingsHover {
            get {
                return ResourceManager.GetString("ProfileLaunchControl_LaunchSettingsHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string ProfileLaunchControl_PlayLabel {
            get {
                return ResourceManager.GetString("ProfileLaunchControl_PlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Profile.
        /// </summary>
        public static string ProfileLaunchControl_SwitchProfileHover {
            get {
                return ResourceManager.GetString("ProfileLaunchControl_SwitchProfileHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGENTS.
        /// </summary>
        public static string Progression_Agents {
            get {
                return ResourceManager.GetString("Progression_Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATTLEPASS.
        /// </summary>
        public static string Progression_Battlepass {
            get {
                return ResourceManager.GetString("Progression_Battlepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED!.
        /// </summary>
        public static string Progression_Battlepass_Completed {
            get {
                return ResourceManager.GetString("Progression_Battlepass_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Tier: .
        /// </summary>
        public static string Progression_Battlepass_CurrTier {
            get {
                return ResourceManager.GetString("Progression_Battlepass_CurrTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string SettingsGeneral_LanguageChange {
            get {
                return ResourceManager.GetString("SettingsGeneral_LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        public static string SettingsGeneral_SelLang {
            get {
                return ResourceManager.GetString("SettingsGeneral_SelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Volume:.
        /// </summary>
        public static string SettingsGeneral_SoundSetting {
            get {
                return ResourceManager.GetString("SettingsGeneral_SoundSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size:.
        /// </summary>
        public static string SettingsGeneral_WindowSize {
            get {
                return ResourceManager.GetString("SettingsGeneral_WindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsTab_About {
            get {
                return ResourceManager.GetString("SettingsTab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsTab_General {
            get {
                return ResourceManager.GetString("SettingsTab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALORANT Settings.
        /// </summary>
        public static string SettingsTab_VALSet {
            get {
                return ResourceManager.GetString("SettingsTab_VALSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED BUNDLE.
        /// </summary>
        public static string Store_FeaturedBundleLabel {
            get {
                return ResourceManager.GetString("Store_FeaturedBundleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY OFFERS.
        /// </summary>
        public static string Store_FeaturedDailyLabel {
            get {
                return ResourceManager.GetString("Store_FeaturedDailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string StorePopup_BackLabel {
            get {
                return ResourceManager.GetString("StorePopup_BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHROMAS.
        /// </summary>
        public static string StorePopup_ChromaLabel {
            get {
                return ResourceManager.GetString("StorePopup_ChromaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVELS.
        /// </summary>
        public static string StorePopup_LevelsLabel {
            get {
                return ResourceManager.GetString("StorePopup_LevelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the project!.
        /// </summary>
        public static string Support_ButtonText {
            get {
                return ResourceManager.GetString("Support_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist is always going to be free and open-sourced. Choosing to support the project will allow us to continue with development and create some more unique features. Thank you &lt;3.
        /// </summary>
        public static string Support_Description {
            get {
                return ResourceManager.GetString("Support_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Assist!.
        /// </summary>
        public static string Support_Title {
            get {
                return ResourceManager.GetString("Support_Title", resourceCulture);
            }
        }
    }
}
