//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist.
        /// </summary>
        public static string AssistTitle {
            get {
                return ResourceManager.GetString("AssistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Authentication_LoginText {
            get {
                return ResourceManager.GetString("Authentication_LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Authentication_MultiFactorCodeText {
            get {
                return ResourceManager.GetString("Authentication_MultiFactorCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your MultiFactor Code.
        /// </summary>
        public static string Authentication_MultiFactorDescription {
            get {
                return ResourceManager.GetString("Authentication_MultiFactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Authentication_PasswordText {
            get {
                return ResourceManager.GetString("Authentication_PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riot Client.
        /// </summary>
        public static string Authentication_RiotClientTitle {
            get {
                return ResourceManager.GetString("Authentication_RiotClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Riot Games Client..
        /// </summary>
        public static string Authentication_RiotClientTitleDescription {
            get {
                return ResourceManager.GetString("Authentication_RiotClientTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with the Riot Client! When you login please make sure you have ”Remember Me” Enabled. Select all remember me options when logining in or it will not be valid. Click Login when you are ready!.
        /// </summary>
        public static string Authentication_RiotClientTitleInstructions {
            get {
                return ResourceManager.GetString("Authentication_RiotClientTitleInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Riot Games Username and Password. Recommended.
        /// </summary>
        public static string Authentication_UsernamePasswordDescription {
            get {
                return ResourceManager.GetString("Authentication_UsernamePasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password.
        /// </summary>
        public static string Authentication_UsernamePasswordTitle {
            get {
                return ResourceManager.GetString("Authentication_UsernamePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Authentication_UsernameText {
            get {
                return ResourceManager.GetString("Authentication_UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string GameLaunch_PlayText {
            get {
                return ResourceManager.GetString("GameLaunch_PlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Patchline:.
        /// </summary>
        public static string GameLaunch_SelectedPatchlineText {
            get {
                return ResourceManager.GetString("GameLaunch_SelectedPatchlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Navigation_BackText {
            get {
                return ResourceManager.GetString("Navigation_BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string NavigationBar_Dashboard {
            get {
                return ResourceManager.GetString("NavigationBar_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        public static string NavigationBar_Progression {
            get {
                return ResourceManager.GetString("NavigationBar_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string NavigationBar_Store {
            get {
                return ResourceManager.GetString("NavigationBar_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOSS.
        /// </summary>
        public static string Profile_LossText {
            get {
                return ResourceManager.GetString("Profile_LossText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WON.
        /// </summary>
        public static string Profile_WonText {
            get {
                return ResourceManager.GetString("Profile_WonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string ProfileManager_AddAccountText {
            get {
                return ResourceManager.GetString("ProfileManager_AddAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string ProfileManager_LogoutText {
            get {
                return ResourceManager.GetString("ProfileManager_LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ProfileManager_ManageAccountText {
            get {
                return ResourceManager.GetString("ProfileManager_ManageAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Missions.
        /// </summary>
        public static string Progression_DailyMissions {
            get {
                return ResourceManager.GetString("Progression_DailyMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Missions.
        /// </summary>
        public static string Progression_WeeklyMissions {
            get {
                return ResourceManager.GetString("Progression_WeeklyMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Store_FeaturedText {
            get {
                return ResourceManager.GetString("Store_FeaturedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Store_OffersText {
            get {
                return ResourceManager.GetString("Store_OffersText", resourceCulture);
            }
        }
    }
}
