//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an Account?.
        /// </summary>
        public static string AssistAccount_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AssistAccount_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string AssistAccount_CreateAccount {
            get {
                return ResourceManager.GetString("AssistAccount_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an Account?.
        /// </summary>
        public static string AssistAccount_DontHaveAccount {
            get {
                return ResourceManager.GetString("AssistAccount_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Login.
        /// </summary>
        public static string Authentication_CloudLogin {
            get {
                return ResourceManager.GetString("Authentication_CloudLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all ”Remember Me” options to successfully login..
        /// </summary>
        public static string Authentication_CloudLoginInstructions {
            get {
                return ResourceManager.GetString("Authentication_CloudLoginInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended w/2FA: Web Login, Without 2FA: Username/Password.
        /// </summary>
        public static string Authentication_Description {
            get {
                return ResourceManager.GetString("Authentication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Riot Client.
        /// </summary>
        public static string Authentication_LaunchRiotClient {
            get {
                return ResourceManager.GetString("Authentication_LaunchRiotClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Register.
        /// </summary>
        public static string Authentication_LoginRegisterText {
            get {
                return ResourceManager.GetString("Authentication_LoginRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Authentication_LoginText {
            get {
                return ResourceManager.GetString("Authentication_LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Riot Client.
        /// </summary>
        public static string Authentication_LoginWithRiotClient {
            get {
                return ResourceManager.GetString("Authentication_LoginWithRiotClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Authentication_MultiFactorCodeText {
            get {
                return ResourceManager.GetString("Authentication_MultiFactorCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your MultiFactor Code.
        /// </summary>
        public static string Authentication_MultiFactorDescription {
            get {
                return ResourceManager.GetString("Authentication_MultiFactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Authentication_PasswordText {
            get {
                return ResourceManager.GetString("Authentication_PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riot Client.
        /// </summary>
        public static string Authentication_RiotClientTitle {
            get {
                return ResourceManager.GetString("Authentication_RiotClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your Riot Games Client..
        /// </summary>
        public static string Authentication_RiotClientTitleDescription {
            get {
                return ResourceManager.GetString("Authentication_RiotClientTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you login select all ”Remember Me” options to successfully login..
        /// </summary>
        public static string Authentication_RiotClientTitleInstructions {
            get {
                return ResourceManager.GetString("Authentication_RiotClientTitleInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Enable the launching of VALORANT, please select yes. This will ask you to login once again..
        /// </summary>
        public static string Authentication_SelectionDescription {
            get {
                return ResourceManager.GetString("Authentication_SelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enable Launching?.
        /// </summary>
        public static string Authentication_SelectionTitle {
            get {
                return ResourceManager.GetString("Authentication_SelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password.
        /// </summary>
        public static string Authentication_UsernamePasswordTitle {
            get {
                return ResourceManager.GetString("Authentication_UsernamePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Authentication_UsernameText {
            get {
                return ResourceManager.GetString("Authentication_UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Login....
        /// </summary>
        public static string Authentication_WaitingForLogin {
            get {
                return ResourceManager.GetString("Authentication_WaitingForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Common_Account {
            get {
                return ResourceManager.GetString("Common_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist.
        /// </summary>
        public static string Common_Assist {
            get {
                return ResourceManager.GetString("Common_Assist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist Account Required.
        /// </summary>
        public static string Common_AssistAccountRequired {
            get {
                return ResourceManager.GetString("Common_AssistAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_BackText {
            get {
                return ResourceManager.GetString("Common_BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Common_Chat {
            get {
                return ResourceManager.GetString("Common_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Updates....
        /// </summary>
        public static string Common_CheckingForUpdate {
            get {
                return ResourceManager.GetString("Common_CheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Common_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Common_Connect {
            get {
                return ResourceManager.GetString("Common_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Common_Day {
            get {
                return ResourceManager.GetString("Common_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Common_Day_Plural {
            get {
                return ResourceManager.GetString("Common_Day_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Common_Details {
            get {
                return ResourceManager.GetString("Common_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Common_Disconnect {
            get {
                return ResourceManager.GetString("Common_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Common_Enable {
            get {
                return ResourceManager.GetString("Common_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Message...
        /// </summary>
        public static string Common_EnterMessage {
            get {
                return ResourceManager.GetString("Common_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Common_Expired {
            get {
                return ResourceManager.GetString("Common_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Common_Export {
            get {
                return ResourceManager.GetString("Common_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Common_Hour {
            get {
                return ResourceManager.GetString("Common_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Common_Hour_Plural {
            get {
                return ResourceManager.GetString("Common_Hour_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Common_Import {
            get {
                return ResourceManager.GetString("Common_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Common_Information {
            get {
                return ResourceManager.GetString("Common_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Common_Launch {
            get {
                return ResourceManager.GetString("Common_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Common_Logout {
            get {
                return ResourceManager.GetString("Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Common_Manage {
            get {
                return ResourceManager.GetString("Common_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Since.
        /// </summary>
        public static string Common_MemberSince {
            get {
                return ResourceManager.GetString("Common_MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Common_Minute {
            get {
                return ResourceManager.GetString("Common_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Common_Minute_Plural {
            get {
                return ResourceManager.GetString("Common_Minute_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Common_Month {
            get {
                return ResourceManager.GetString("Common_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Common_Month_Plural {
            get {
                return ResourceManager.GetString("Common_Month_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Common_Notification {
            get {
                return ResourceManager.GetString("Common_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Common_Party {
            get {
                return ResourceManager.GetString("Common_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTY.
        /// </summary>
        public static string Common_Party_Caps {
            get {
                return ResourceManager.GetString("Common_Party_Caps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Common_Play {
            get {
                return ResourceManager.GetString("Common_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Common_Region {
            get {
                return ResourceManager.GetString("Common_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Common_Register {
            get {
                return ResourceManager.GetString("Common_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting....
        /// </summary>
        public static string Common_Selecting {
            get {
                return ResourceManager.GetString("Common_Selecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Common_Send {
            get {
                return ResourceManager.GetString("Common_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Common_SignIn {
            get {
                return ResourceManager.GetString("Common_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Common_Support {
            get {
                return ResourceManager.GetString("Common_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter.
        /// </summary>
        public static string Common_Supporter {
            get {
                return ResourceManager.GetString("Common_Supporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter Pro.
        /// </summary>
        public static string Common_SupporterPro {
            get {
                return ResourceManager.GetString("Common_SupporterPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Common_Switch {
            get {
                return ResourceManager.GetString("Common_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Common_Training {
            get {
                return ResourceManager.GetString("Common_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Common_Updating {
            get {
                return ResourceManager.GetString("Common_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Common_Username {
            get {
                return ResourceManager.GetString("Common_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Common_Year {
            get {
                return ResourceManager.GetString("Common_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Common_Years_Plural {
            get {
                return ResourceManager.GetString("Common_Years_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        public static string Dodge_AddPlayer {
            get {
                return ResourceManager.GetString("Dodge_AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist DODGE allows for you to be warned about players on your team and game. Add, Remove, Edit, and overall manage your own DODGE List. Additionally, a Global List is available for all players..
        /// </summary>
        public static string Dodge_Description {
            get {
                return ResourceManager.GetString("Dodge_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODGE LIST.
        /// </summary>
        public static string Dodge_DodgeList {
            get {
                return ResourceManager.GetString("Dodge_DodgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Player.
        /// </summary>
        public static string Dodge_EditPlayer {
            get {
                return ResourceManager.GetString("Dodge_EditPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your list is empty..
        /// </summary>
        public static string Dodge_ListEmpty {
            get {
                return ResourceManager.GetString("Dodge_ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODGE.
        /// </summary>
        public static string Dodge_Title {
            get {
                return ResourceManager.GetString("Dodge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Comms.
        /// </summary>
        public static string DodgeCategory_BadComms {
            get {
                return ResourceManager.GetString("DodgeCategory_BadComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Teammate.
        /// </summary>
        public static string DodgeCategory_BadTeammate {
            get {
                return ResourceManager.GetString("DodgeCategory_BadTeammate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string DodgeCategory_Bot {
            get {
                return ResourceManager.GetString("DodgeCategory_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheater.
        /// </summary>
        public static string DodgeCategory_Cheater {
            get {
                return ResourceManager.GetString("DodgeCategory_Cheater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Griefer.
        /// </summary>
        public static string DodgeCategory_Griefer {
            get {
                return ResourceManager.GetString("DodgeCategory_Griefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string DodgeCategory_Ignore {
            get {
                return ResourceManager.GetString("DodgeCategory_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smurf.
        /// </summary>
        public static string DodgeCategory_Smurf {
            get {
                return ResourceManager.GetString("DodgeCategory_Smurf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Sniper.
        /// </summary>
        public static string DodgeCategory_Streamsniper {
            get {
                return ResourceManager.GetString("DodgeCategory_Streamsniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrower.
        /// </summary>
        public static string DodgeCategory_Thrower {
            get {
                return ResourceManager.GetString("DodgeCategory_Thrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic.
        /// </summary>
        public static string DodgeCategory_Toxic {
            get {
                return ResourceManager.GetString("DodgeCategory_Toxic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Trading.
        /// </summary>
        public static string DodgeCategory_Wintrader {
            get {
                return ResourceManager.GetString("DodgeCategory_Wintrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tracker Profile.
        /// </summary>
        public static string Live_OpenTracker {
            get {
                return ResourceManager.GetString("Live_OpenTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string ProfileManager_AddAccountText {
            get {
                return ResourceManager.GetString("ProfileManager_AddAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut.
        /// </summary>
        public static string ProfileManager_CreateShortcut {
            get {
                return ResourceManager.GetString("ProfileManager_CreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a shortcut allows you to boot into an account with ease. Select a Patchline and an icon will showup on your desktop..
        /// </summary>
        public static string ProfileManager_CreateShortcutDescription {
            get {
                return ResourceManager.GetString("ProfileManager_CreateShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Shortcut.
        /// </summary>
        public static string ProfileManager_CreateShortcutTitle {
            get {
                return ResourceManager.GetString("ProfileManager_CreateShortcutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string ProfileManager_Expired {
            get {
                return ResourceManager.GetString("ProfileManager_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Launch.
        /// </summary>
        public static string ProfileManager_GameLaunch {
            get {
                return ResourceManager.GetString("ProfileManager_GameLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Game Launching.
        /// </summary>
        public static string ProfileManager_GameLaunchTitle {
            get {
                return ResourceManager.GetString("ProfileManager_GameLaunchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ProfileManager_ManageAccountText {
            get {
                return ResourceManager.GetString("ProfileManager_ManageAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Riot Client Found.
        /// </summary>
        public static string ProfileManager_NoRiotClient {
            get {
                return ResourceManager.GetString("ProfileManager_NoRiotClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ProfileManager_Remove {
            get {
                return ResourceManager.GetString("ProfileManager_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord Rich Presence.
        /// </summary>
        public static string RichPres_Enable {
            get {
                return ResourceManager.GetString("RichPres_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Image.
        /// </summary>
        public static string RichPres_LargeImage {
            get {
                return ResourceManager.GetString("RichPres_LargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Settings.
        /// </summary>
        public static string RichPres_Privacy {
            get {
                return ResourceManager.GetString("RichPres_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gamemode.
        /// </summary>
        public static string RichPres_ShowGamemode {
            get {
                return ResourceManager.GetString("RichPres_ShowGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Party Size.
        /// </summary>
        public static string RichPres_ShowParty {
            get {
                return ResourceManager.GetString("RichPres_ShowParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rank.
        /// </summary>
        public static string RichPres_ShowRank {
            get {
                return ResourceManager.GetString("RichPres_ShowRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Score.
        /// </summary>
        public static string RichPres_ShowScore {
            get {
                return ResourceManager.GetString("RichPres_ShowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Image.
        /// </summary>
        public static string RichPres_SmallImage {
            get {
                return ResourceManager.GetString("RichPres_SmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist Account.
        /// </summary>
        public static string Settings_AssistAccount {
            get {
                return ResourceManager.GetString("Settings_AssistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Game Mode:.
        /// </summary>
        public static string Settings_EnableGameMode {
            get {
                return ResourceManager.GetString("Settings_EnableGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPU:.
        /// </summary>
        public static string Settings_EnableGpu {
            get {
                return ResourceManager.GetString("Settings_EnableGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling GPU will allow Assist to Perform better, but at the cost of using more resources..
        /// </summary>
        public static string Settings_EnableGpuWarning {
            get {
                return ResourceManager.GetString("Settings_EnableGpuWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Settings.
        /// </summary>
        public static string Settings_Launch {
            get {
                return ResourceManager.GetString("Settings_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string Settings_Resolution {
            get {
                return ResourceManager.GetString("Settings_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required for Settings to Apply..
        /// </summary>
        public static string Settings_RestartReq {
            get {
                return ResourceManager.GetString("Settings_RestartReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riot Accounts.
        /// </summary>
        public static string Settings_RiotAccounts {
            get {
                return ResourceManager.GetString("Settings_RiotAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Settings_Sound {
            get {
                return ResourceManager.GetString("Settings_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an Assist Account.
        /// </summary>
        public static string Setup_CreateAssistAccount {
            get {
                return ResourceManager.GetString("Setup_CreateAssistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using an Assist Account allows you to unlock the full suite of tools that assist offers..
        /// </summary>
        public static string Setup_CreateAssistAccountDescription {
            get {
                return ResourceManager.GetString("Setup_CreateAssistAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mode Only.
        /// </summary>
        public static string Setup_GameEnabled {
            get {
                return ResourceManager.GetString("Setup_GameEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist will only use Game Mode. All Launcher Features are disabled..
        /// </summary>
        public static string Setup_GameEnabledDescription {
            get {
                return ResourceManager.GetString("Setup_GameEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language.
        /// </summary>
        public static string Setup_LanguageSelection {
            get {
                return ResourceManager.GetString("Setup_LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Mode Only.
        /// </summary>
        public static string Setup_LauncherEnabled {
            get {
                return ResourceManager.GetString("Setup_LauncherEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist will only act as a launcher. Game Mode will be turned off..
        /// </summary>
        public static string Setup_LauncherEnabledDescription {
            get {
                return ResourceManager.GetString("Setup_LauncherEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Suite of tools are at your disposal..
        /// </summary>
        public static string Setup_LauncherGameDescription {
            get {
                return ResourceManager.GetString("Setup_LauncherGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher &amp; Game Mode Enabled.
        /// </summary>
        public static string Setup_LauncherGameEnabled {
            get {
                return ResourceManager.GetString("Setup_LauncherGameEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This can be changed in the settings later..
        /// </summary>
        public static string Setup_NoteCanBeChanged {
            get {
                return ResourceManager.GetString("Setup_NoteCanBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Assist Account.
        /// </summary>
        public static string Setup_SkipAssistAccount {
            get {
                return ResourceManager.GetString("Setup_SkipAssistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip creating an Assist Account and receive only basic features..
        /// </summary>
        public static string Setup_SkipAssistAccountDescription {
            get {
                return ResourceManager.GetString("Setup_SkipAssistAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be a quick setup to setup your client the way you want to..
        /// </summary>
        public static string Setup_WelcomeDescription {
            get {
                return ResourceManager.GetString("Setup_WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Assist.
        /// </summary>
        public static string Setup_WelcomeText {
            get {
                return ResourceManager.GetString("Setup_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string Social_Discord {
            get {
                return ResourceManager.GetString("Social_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Discord.
        /// </summary>
        public static string Social_DiscordLogin {
            get {
                return ResourceManager.GetString("Social_DiscordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string Social_Twitch {
            get {
                return ResourceManager.GetString("Social_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Social_X {
            get {
                return ResourceManager.GetString("Social_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to login....
        /// </summary>
        public static string Startup_AttemptingToLogin {
            get {
                return ResourceManager.GetString("Startup_AttemptingToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Account.
        /// </summary>
        public static string Startup_SwapAccount {
            get {
                return ResourceManager.GetString("Startup_SwapAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Store_Accessories {
            get {
                return ResourceManager.GetString("Store_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Items.
        /// </summary>
        public static string Store_BundleItemsContains {
            get {
                return ResourceManager.GetString("Store_BundleItemsContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Overlook.
        /// </summary>
        public static string Store_BundleOverlook {
            get {
                return ResourceManager.GetString("Store_BundleOverlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Offers.
        /// </summary>
        public static string Store_DailyOffers {
            get {
                return ResourceManager.GetString("Store_DailyOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Bundles.
        /// </summary>
        public static string Store_FeaturedBundles {
            get {
                return ResourceManager.GetString("Store_FeaturedBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Market.
        /// </summary>
        public static string Store_NightMarket {
            get {
                return ResourceManager.GetString("Store_NightMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store_Store {
            get {
                return ResourceManager.GetString("Store_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascent.
        /// </summary>
        public static string VALORANT_Ascent {
            get {
                return ResourceManager.GetString("VALORANT_Ascent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astra.
        /// </summary>
        public static string VALORANT_Astra {
            get {
                return ResourceManager.GetString("VALORANT_Astra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind.
        /// </summary>
        public static string VALORANT_Bind {
            get {
                return ResourceManager.GetString("VALORANT_Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach.
        /// </summary>
        public static string VALORANT_Breach {
            get {
                return ResourceManager.GetString("VALORANT_Breach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeze.
        /// </summary>
        public static string VALORANT_Breeze {
            get {
                return ResourceManager.GetString("VALORANT_Breeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brimstone.
        /// </summary>
        public static string VALORANT_Brimstone {
            get {
                return ResourceManager.GetString("VALORANT_Brimstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber.
        /// </summary>
        public static string VALORANT_Chamber {
            get {
                return ResourceManager.GetString("VALORANT_Chamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clove.
        /// </summary>
        public static string VALORANT_Clove {
            get {
                return ResourceManager.GetString("VALORANT_Clove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Game.
        /// </summary>
        public static string VALORANT_CustomGame {
            get {
                return ResourceManager.GetString("VALORANT_CustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cypher.
        /// </summary>
        public static string VALORANT_Cypher {
            get {
                return ResourceManager.GetString("VALORANT_Cypher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlock.
        /// </summary>
        public static string VALORANT_Deadlock {
            get {
                return ResourceManager.GetString("VALORANT_Deadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string VALORANT_District {
            get {
                return ResourceManager.GetString("VALORANT_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drift.
        /// </summary>
        public static string VALORANT_Drift {
            get {
                return ResourceManager.GetString("VALORANT_Drift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade.
        /// </summary>
        public static string VALORANT_Fade {
            get {
                return ResourceManager.GetString("VALORANT_Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture.
        /// </summary>
        public static string VALORANT_Fracture {
            get {
                return ResourceManager.GetString("VALORANT_Fracture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gekko.
        /// </summary>
        public static string VALORANT_Gekko {
            get {
                return ResourceManager.GetString("VALORANT_Gekko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbor.
        /// </summary>
        public static string VALORANT_Harbor {
            get {
                return ResourceManager.GetString("VALORANT_Harbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven.
        /// </summary>
        public static string VALORANT_Haven {
            get {
                return ResourceManager.GetString("VALORANT_Haven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icebox.
        /// </summary>
        public static string VALORANT_Icebox {
            get {
                return ResourceManager.GetString("VALORANT_Icebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iso.
        /// </summary>
        public static string VALORANT_Iso {
            get {
                return ResourceManager.GetString("VALORANT_Iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jett.
        /// </summary>
        public static string VALORANT_Jett {
            get {
                return ResourceManager.GetString("VALORANT_Jett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasbah.
        /// </summary>
        public static string VALORANT_Kasbah {
            get {
                return ResourceManager.GetString("VALORANT_Kasbah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAY/O.
        /// </summary>
        public static string VALORANT_KAYO {
            get {
                return ResourceManager.GetString("VALORANT_KAYO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killjoy.
        /// </summary>
        public static string VALORANT_Killjoy {
            get {
                return ResourceManager.GetString("VALORANT_Killjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotus.
        /// </summary>
        public static string VALORANT_Lotus {
            get {
                return ResourceManager.GetString("VALORANT_Lotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon.
        /// </summary>
        public static string VALORANT_Neon {
            get {
                return ResourceManager.GetString("VALORANT_Neon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omen.
        /// </summary>
        public static string VALORANT_Omen {
            get {
                return ResourceManager.GetString("VALORANT_Omen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearl.
        /// </summary>
        public static string VALORANT_Pearl {
            get {
                return ResourceManager.GetString("VALORANT_Pearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoenix.
        /// </summary>
        public static string VALORANT_Phoenix {
            get {
                return ResourceManager.GetString("VALORANT_Phoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piazza.
        /// </summary>
        public static string VALORANT_Piazza {
            get {
                return ResourceManager.GetString("VALORANT_Piazza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raze.
        /// </summary>
        public static string VALORANT_Raze {
            get {
                return ResourceManager.GetString("VALORANT_Raze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reyna.
        /// </summary>
        public static string VALORANT_Reyna {
            get {
                return ResourceManager.GetString("VALORANT_Reyna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage.
        /// </summary>
        public static string VALORANT_Sage {
            get {
                return ResourceManager.GetString("VALORANT_Sage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skye.
        /// </summary>
        public static string VALORANT_Skye {
            get {
                return ResourceManager.GetString("VALORANT_Skye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sova.
        /// </summary>
        public static string VALORANT_Sova {
            get {
                return ResourceManager.GetString("VALORANT_Sova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string VALORANT_Split {
            get {
                return ResourceManager.GetString("VALORANT_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string VALORANT_Sunset {
            get {
                return ResourceManager.GetString("VALORANT_Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Range.
        /// </summary>
        public static string VALORANT_TheRange {
            get {
                return ResourceManager.GetString("VALORANT_TheRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temple.
        /// </summary>
        public static string VALORANT_Unknown {
            get {
                return ResourceManager.GetString("VALORANT_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viper.
        /// </summary>
        public static string VALORANT_Viper {
            get {
                return ResourceManager.GetString("VALORANT_Viper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoru.
        /// </summary>
        public static string VALORANT_Yoru {
            get {
                return ResourceManager.GetString("VALORANT_Yoru", resourceCulture);
            }
        }
    }
}
